---
# tasks file for ansible-role-easywall
- name: Ensure iptables is present.
  package:
    name: "iptables"
    state: "present"

- import_tasks: disable-other-firewalls.yml
  when: firewall_disable_firewalld or firewall_disable_ufw

- name: "install apt-transport-https for https apt sources"
  apt:
    state: present
    update_cache: true
    name: apt-transport-https

- name: "add easywall apt key from ubuntu keyserver"
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: D88D7689C1624EE3
    state: present

- name: "add easywall apt repository"
  apt_repository:
    repo: "deb https://apt.wdkro.de/ stable main"
    filename: "easywall"
    state: present

- name: "install easywall package"
  apt:
    state: present
    update_cache: true
    name: easywall

- name: "set up username and password"
  shell: |
    cd /opt/easywall
    python3 easywall_web/passwd.py -u {{ easywall_username }} -p '{{ easywall_password }}'
  when: webinterface and easywall_username != "" and easywall_password != ""

- name: "stop easywall-web and disable service when webinterface is false"
  systemd:
    name: easywall-web
    enabled: no
    state: stopped
    masked: yes
  when: not webinterface

- name: "ensure easywall is restarted"
  systemd:
    name: easywall
    state: restarted

- name: "ensure easywall-web is restarted"
  systemd:
    name: easywall-web
    state: restarted
