---
# tasks file for ansible-role-easywall
- name: Ensure iptables is present.
  package:
    name: "iptables"
    state: "present"

- import_tasks: disable-other-firewalls.yml
  when: firewall_disable_firewalld or firewall_disable_ufw

- name: "install apt-transport-https for https apt sources"
  apt:
    state: present
    update_cache: true
    name: apt-transport-https

- name: "add easywall apt key from ubuntu keyserver"
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: D88D7689C1624EE3
    state: present

- name: "add easywall apt repository"
  apt_repository:
    repo: "deb https://apt.wdkro.de/ stable main"
    filename: "easywall"
    state: present

- name: "install easywall package"
  apt:
    state: present
    update_cache: true
    name: easywall
  when: not install_updates | bool

- name: "install or upgrade easywall package to latest version"
  apt:
    state: latest
    update_cache: true
    name: easywall
  when: install_updates | bool

- name: update configuration file - /opt/easywall/config/log.ini
  template:
    src: opt/easywall/config/log.ini.j2
    dest: /opt/easywall/config/log.ini
    owner: easywall
    group: easywall
    mode: "0644"
  notify:
    - "restart-core"
    - "restart-web"
  when: overwrite_config | bool

- name: update configuration file - /opt/easywall/config/web.ini
  template:
    src: opt/easywall/config/web.ini.j2
    dest: /opt/easywall/config/web.ini
    owner: easywall
    group: easywall
    mode: "0644"
  notify: "restart-web"
  when: overwrite_config | bool

- name: update configuration file - /opt/easywall/config/easywall.ini
  template:
    src: opt/easywall/config/easywall.ini.j2
    dest: /opt/easywall/config/easywall.ini
    owner: easywall
    group: easywall
    mode: "0644"
  notify: "restart-core"
  when: overwrite_config | bool

- name: "set up username and password"
  shell: |
    cd /opt/easywall
    python3 easywall/web/passwd.py -u {{ web_username }} -p '{{ web_password }}'
  when: webinterface and web_username | length > 0 and web_password | length > 0
  notify: "restart-web"

- name: "copy ssl certificate on the remote system to easywall install dir"
  copy:
    src: "{{ ssl_cert_path }}"
    dest: "/opt/easywall/ssl/easywall.crt"
    remote_src: true
    mode: "0600"
  when: webinterface and ssl_cert_path | length > 0
  notify: "restart-web"

- name: "copy ssl certificate key on the remote system to easywall install dir"
  copy:
    src: "{{ ssl_key_path }}"
    dest: "/opt/easywall/ssl/easywall.key"
    remote_src: true
    mode: "0600"
  when: webinterface and ssl_key_path | length > 0
  notify: "restart-web"

- name: "stop easywall-web and disable service when webinterface is false"
  systemd:
    name: easywall-web
    enabled: false
    state: stopped
    masked: true
  when: not webinterface
